//Unit Stats based on Beginner worlds
const SpotterNaki = {Strength: 1, Defense: 1, Speed: 120, RecruitmentTime: 8, RecruitingLocation : "Marshlands", Effective0: "nothing", Effective1: null, Effective2: null, Effective3: null, Effective4: null, Effective5: null, Weak: "Nothing"};
const DruidNaki = {Strength: 25, Defense: 25, Speed: 300, RecruitmentTime: 32,  RecruitingLocation : "Marshlands", Effective0: "Forest Spirit", Effective1: "Grass Spirit", Effective2: "Elder Spirit", Effective3: null, Effective4: null, Effective5: null, Weak: "Nothing" };
const GrassSpirit = {Strength: 20, Defense: 40, Speed: 500, RecruitmentTime: 40,  RecruitingLocation : "Marshlands", Effective0: "Guard Naki", Effective1: "Athlas", Effective2: null, Effective3: null, Effective4: null, Effective5: null, Weak: "Nothing"};
const ForestSpirit = {Strength: 30, Defense: 60, Speed: 475 ,RecruitmentTime: 60,  RecruitingLocation : "Marshlands", Effective0: "Guard Naki", Effective1: "Athlas", Effective2: null, Effective3: null, Effective4: null, Effective5: null, Weak: "Nothing"};
const GuardNaki = {Strength: 100, Defense: 50, Speed: 300, RecruitmentTime: 80,  RecruitingLocation : "Marshlands", Effective0: "Druid Naki", Effective1: "Elder Spirit", Effective2: null, Effective3: null, Effective4: null, Effective5: null, Weak: "Nothing"};
const ElderSpirit = {Strength: 100, Defense: 1000, Speed: 750 ,RecruitmentTime: 400, RecruitingLocation : "Marshlands", Effective0: "Athlas", Effective1: "Wasty", Effective2: null, Effective3: null, Effective4: null, Effective5: null, Weak: "Nothing"};
const Pangoan = {Strength: 200, Defense: 200, Speed: 400 ,RecruitmentTime: 100, RecruitingLocation : "Marshlands", Effective0: "nothing", Effective1: null, Effective2: null, Effective3: null, Effective4: null, Effective5: null, Weak: "Nothing"};
const Athlas = {Strength: 800, Defense: 600, Speed: 76.66,RecruitmentTime: 100, RecruitingLocation : "Marshlands", Effective0: "Marshy", Effective1: "Teryx", Effective2: "Raider", Effective3: "Ovivi", Effective4: null, Effective5: null,Weak: "Nothing"};
const Nyxi = {Strength: 50, Defense: 20, Speed: 250 ,RecruitmentTime: 24,  RecruitingLocation : "Marshlands", Effective0: "Elder Spirit", Effective1: "Guard Naki", Effective2: "Druid Naki", Effective3: null, Effective4: null, Effective5: null,Weak: "Nothing"};
const Ranax = {Strength: 250, Defense: 10, Speed: 350, RecruitmentTime: 80,  RecruitingLocation : "Marshlands", Effective0: "Marshy", Effective1: "Grass Spirit", Effective2: "Forest Spirit", Effective3: null, Effective4: null, Effective5: null,Weak: "Nothing"};
const Ovivi = {Strength: 10, Defense: 150, Speed: 10 ,RecruitmentTime: 10,  RecruitingLocation : "Marshlands", Effective0: "Grass Spirit", Effective1: "Forest Spirit", Effective2: "Elder Spirit", Effective3: null, Effective4: null, Effective5: null,Weak: "Nothing"};
const Teryx = {Strength: 90, Defense: 20, Speed: 250 ,RecruitmentTime: 20.41,  RecruitingLocation : "Marshlands", Effective0: "Druid Naki", Effective1: " rass Spirit", Effective2: "Forest Spirit", Effective3: "Guard Naki", Effective4: "Elder spirit", Effective5: null, Weak: "Nothing"};
const Raider = {Strength: 5, Defense: 1, Speed: 200 ,RecruitmentTime: 6.8, RecruitingLocation : "Marshlands", Effective0: "nothing", Effective1: null, Effective2: null, Effective3: null, Effective4: null, Effective5: null, Weak: "Nothing"};
const OviviHero = {Strength: 50000, Defense: 10, Speed: 10 ,RecruitmentTime: 10, RecruitingLocation : "Marshlands", Effective0: "Grass Spirit", Effective1: "Forest Spirit", Effective2: "Elder Spirit", Effective3: null, Effective4: null, Effective5: null,Weak: "Nothing"};

//Oder of Units in Array has to match order of Units in HTML
const UnitArray = [SpotterNaki, DruidNaki, GrassSpirit, ForestSpirit, GuardNaki, ElderSpirit, Pangoan, Athlas, Nyxi, Ranax, Ovivi, Teryx, Raider, OviviHero];
const unitArray = {"Spotter Naki" : SpotterNaki, "Druid Naki": DruidNaki, "Grass Spirit": GrassSpirit, "Forest Spirit": ForestSpirit, "Guard Naki": GuardNaki, "Elder Spirit": ElderSpirit, "Pangoan": Pangoan, "Athlas": Athlas,"Nyxi": Nyxi,"Ranax": Ranax, "Ovivi": Ovivi, "Teryx": Teryx, "Raider": Raider, "Ovivi Hero": OviviHero};
const unitNamesArray = ["Spotter Naki", "Druid Naki", "Grass Spirit", "Forest Spirit", "Guard Naki", "Elder Spirit", "Pangoan", "Athlas", "Nyxi", "Ranax", "Ovivi", "Teryx", "Raider", "Ovivi Hero"];

